# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/models.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'proto/models.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12proto/models.proto\x12\x06models\"A\n\x07\x43ontext\x12\x0e\n\x06value1\x18\x01 \x01(\t\x12\x0e\n\x06value2\x18\x02 \x01(\t\x12\x0b\n\x03\x63on\x18\x03 \x01(\t\x12\t\n\x01v\x18\x04 \x03(\x05\"C\n\rModelARequest\x12\x10\n\x08messages\x18\x01 \x03(\t\x12 \n\x07\x63ontext\x18\x02 \x03(\x0b\x32\x0f.models.Context\"\x1f\n\x0eModelAResponse\x12\r\n\x05reply\x18\x01 \x01(\t\"\x1e\n\rModelBRequest\x12\r\n\x05value\x18\x01 \x01(\x05\" \n\x0eModelBResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\"(\n\x04Task\x12\x0f\n\x07task_id\x18\x01 \x01(\t\x12\x0f\n\x07request\x18\x02 \x01(\x0c\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.models_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CONTEXT']._serialized_start=30
  _globals['_CONTEXT']._serialized_end=95
  _globals['_MODELAREQUEST']._serialized_start=97
  _globals['_MODELAREQUEST']._serialized_end=164
  _globals['_MODELARESPONSE']._serialized_start=166
  _globals['_MODELARESPONSE']._serialized_end=197
  _globals['_MODELBREQUEST']._serialized_start=199
  _globals['_MODELBREQUEST']._serialized_end=229
  _globals['_MODELBRESPONSE']._serialized_start=231
  _globals['_MODELBRESPONSE']._serialized_end=263
  _globals['_TASK']._serialized_start=265
  _globals['_TASK']._serialized_end=305
# @@protoc_insertion_point(module_scope)
