# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: serialization_type_test/test_model.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'serialization_type_test/test_model.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n(serialization_type_test/test_model.proto\"_\n\x0b\x44\x61taMessage\x12\x0e\n\x06int32s\x18\x01 \x03(\x05\x12\x0e\n\x06int64s\x18\x02 \x03(\x03\x12\x0e\n\x06\x66loats\x18\x03 \x03(\x02\x12\x0f\n\x07\x64oubles\x18\x04 \x03(\x01\x12\x0f\n\x07strings\x18\x05 \x03(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'serialization_type_test.test_model_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DATAMESSAGE']._serialized_start=44
  _globals['_DATAMESSAGE']._serialized_end=139
# @@protoc_insertion_point(module_scope)
