name: Proto Compatibility Check

on:
  pull_request:
    paths:
      - '**/*.proto'
  push:
    branches:
      - main

jobs:
  proto-breaking-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current (PR) branch
        uses: actions/checkout@v4

      - name: Set up Buf CLI
        uses: bufbuild/buf-setup-action@v1

      - name: Generate current version protos
        run: |
          mkdir current
          cp -r ./*.proto current/

      - name: Fetch main branch for comparison
        run: |
          git fetch origin main
          mkdir main
          git checkout origin/main -- ./*.proto
          cp -r ./*.proto main/

      - name: Run Buf breaking check
        id: buf_check
        continue-on-error: true
        run: |
          buf breaking --against "main" > buf_output.txt
          echo "exit_code=$?" >> $GITHUB_OUTPUT

      - name: Run custom compatibility check
        if: steps.buf_check.outputs.exit_code != '0'
        run: |
          python .github/scripts/validate_removed_fields_reserved.py

      - name: Fail on actual breaking change
        if: steps.buf_check.outputs.exit_code != '0'
        run: |
          echo "Breaking change detected. Not all removed fields are reserved." >&2
          exit 1