name: Proto Compatibility Check

on:
  pull_request:
    paths:
      - '**/*.proto'

jobs:
  proto-breaking-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Set up Buf CLI
        uses: bufbuild/buf-setup-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Copy current version of .proto files
        run: |
          mkdir -p current
          find . -name "*.proto" -exec cp --parents {} current \;

      - name: Get proto files from master
        run: |
          git fetch origin master
          git checkout origin/master -- .
          mkdir -p master
          find . -name "*.proto" -exec cp --parents {} master \;

      - name: Run proto compatibility check script
        run: |
          python validate_removed_fields_reserved.py

      - name: Show success message
        if: success()
        run: echo "✅ Proto compatibility check passed!"