name: CI-Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis
        ports:
          - 6379:6379
      rabbitmq:
        image: rabbitmq:3-management
        ports:
          - 5672:5672
          - 15672:15672

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4

    - name: Set PYTHONPATH
      run: echo "PYTHONPATH=$PWD" >> $GITHUB_ENV

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest httpx pytest-asyncio

    - name: Gen proto models
      run: | 
        python -m grpc_tools.protoc   -I proto   --python_out=.   --grpc_python_out=.   proto/models.proto
        python -m grpc_tools.protoc   -I tests   --python_out=.   --grpc_python_out=.   tests/example.proto

    - name: Run tests
      run: pytest tests